In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../Datasets/Bouletta/EtsySoldOrderItemsWithReviews2020-2021-2022.csv")

In [3]:
model_map = {"iPhone 12": 1, "iPhone 12 Pro": 2, "Samsung Galaxy S21": 3,"Galaxy Note 20":4,\
             "iPhone 11 Pro Max": 5,"iPhone 12 PRO MAX":6,"Watch Band":7,"iPhone Mini 12":8,\
            "Galaxy Note 20 ULTRA":9,"Galaxy S20 Ultra":10,"iPhone 13 Series":11,
            "Galaxy Note 10 Plus":12,"iPhone 13 Pro":13,"AirPods":14,"Desk Mat":15,
            "Galaxy S20 Plus":16,"iPhone SE":17,"Samsung Galaxy S20":18,"Apple iPhone XS MAX":19,
            "Apple iPhone XR":20,"Apple iPhone X/XS":21,"iPhone 11":22,"Samsung S10":23,
            "Card Holder":24,"Galaxy N10":25,"iPhone 7/8":26,"Women's Wallet":27,
            "Custom order":28,"Organizer":29,"iPhone 14 Series":30,"Galaxy S22 Series":31,"AirTag":32,
            "Mouse Pad":33,"Galaxy S22":34,"Makeup Purse":35,"Huawei Mate 20 Pro":36,
             "Samsung Galaxy S10":37,"Huawei Mate 20 Lite":38,"Samsung Galaxy S8 Plus":39,
             "Samsung Galaxy S10 Plus":40,"Samsung Note 8":41,"Huawei P20 Pro":42,"Samsung Note 10":43,
            "Samsung Galaxy S8":44,"Galaxy S9 Plus":45,"Galaxy S9":47,
            "iPhone XS MAX":48,"Samsung Note 9":46,"iPhone X/XS":49,"Galaxy Note 10+":51,"iPhone X":52}

In [4]:
reversed_dict = {value: key for key, value in model_map.items()}

In [5]:
reversed_seasons = {0:'Winter', 1:'Spring', 2:'Summer',3: 'Fall'}

In [6]:
def map_model(item_name):
    x = False
    for model, number in reversed_dict.items():
        if model == item_name:
            x= True
            return number
    if x == False:
        print(item_name)
df["Item Model"] = df["Item Model"].apply(map_model)

In [7]:
reversed_seasons = {0:'Winter', 1:'Spring', 2:'Summer',3: 'Fall'}
df['Season'] = df['Season'].map(reversed_seasons)

In [8]:
dummy = pd.get_dummies(df, columns=["Season"],prefix="",prefix_sep ="")
dummy = pd.get_dummies(dummy, columns=["Item Model"],prefix="",prefix_sep ="")

In [9]:
dummy_df = pd.get_dummies(df, columns=["Item Model"],prefix="",prefix_sep ="")

In [10]:
dummy_df

,Quantity,Price,Coupon Code,Ship Country,Season,Month,Year,Color,star_rating,message,...,iPhone 11 Pro Max,iPhone 12,iPhone 13 Pro,iPhone 13 Series,iPhone 14 Series,iPhone 7/8,iPhone SE,iPhone X,iPhone X/XS,iPhone XS MAX
0,1,33.50,1,1,Winter,12,2020,2.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1,39.00,1,1,Winter,12,2020,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
2,1,41.50,1,1,Winter,12,2020,1.0,2.0,1.0,...,1,0,0,0,0,0,0,0,0,0
3,1,46.50,1,1,Winter,12,2020,1.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
4,1,39.75,1,1,Winter,12,2020,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,1,48.25,1,1,Winter,1,2022,9.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2249,1,82.99,1,1,Winter,1,2022,0.0,3.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2250,1,48.25,1,1,Winter,1,2022,9.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2251,1,54.19,1,1,Winter,1,2022,-1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2252,1,82.99,1,1,Winter,1,2022,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
s = dummy_df.groupby(['Season'], as_index=True).sum()

In [12]:
s

,Quantity,Price,Coupon Code,Ship Country,Month,Year,Color,star_rating,message,AirPods,...,iPhone 11 Pro Max,iPhone 12,iPhone 13 Pro,iPhone 13 Series,iPhone 14 Series,iPhone 7/8,iPhone SE,iPhone X,iPhone X/XS,iPhone XS MAX
Season,,,,,,,,,,,,,,,,,,,,,
Fall,589,32744.83,586,1655,5881,1184167,1221.0,592.0,80.0,1,...,7,112,8,59,4,3,11,0,0,0
Spring,497,25571.94,495,1132,2016,1000409,1151.0,639.0,102.0,0,...,11,69,8,21,0,11,16,0,0,1
Summer,622,32523.53,621,1990,4376,1255025,1661.0,769.0,122.0,4,...,6,33,10,22,0,6,25,0,0,0
Winter,553,28738.46,551,1477,3410,1113623,1030.0,506.0,85.0,9,...,17,116,2,44,5,8,4,1,5,0

In [13]:
dummy

,Quantity,Price,Coupon Code,Ship Country,Month,Year,Color,star_rating,message,Fall,...,iPhone 11 Pro Max,iPhone 12,iPhone 13 Pro,iPhone 13 Series,iPhone 14 Series,iPhone 7/8,iPhone SE,iPhone X,iPhone X/XS,iPhone XS MAX
0,1,33.50,1,1,12,2020,2.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,39.00,1,1,12,2020,1.0,0.0,0.0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,41.50,1,1,12,2020,1.0,2.0,1.0,0,...,1,0,0,0,0,0,0,0,0,0
3,1,46.50,1,1,12,2020,1.0,0.0,0.0,0,...,0,1,0,0,0,0,0,0,0,0
4,1,39.75,1,1,12,2020,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,1,48.25,1,1,1,2022,9.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2249,1,82.99,1,1,1,2022,0.0,3.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
2250,1,48.25,1,1,1,2022,9.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2251,1,54.19,1,1,1,2022,-1.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2252,1,82.99,1,1,1,2022,0.0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
# s.to_csv("Dummy_GroupBySeason.csv")

In [15]:
dummy.to_csv("DummyModels.csv", index=False)